add_newline = true
format = "$line_break$time$username$hostname$git_branch$git_commit$git_status$exec_time$jobs$exit_code$python$directory$line_break$character"

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold cyan)"
vimcmd_symbol = "[❮](bold yellow)"

[directory]
truncate_to_repo = true
truncation_length = 4

[git_branch]
disabled = false
format = "[$branch]($style) "
style = "bold magenta"

[git_commit]
disabled = false
format = "[$hash]($style) "
style = "bold magenta"

[hostname]
disabled = false
format = "[@$hostname]($style) "
ssh_only = false
style = "bold cyan"

[line_break]
disabled = false

[time]
disabled = false
format = "[$time]($style) "
style = "bold white"

[username]
disabled = false
format = "[$user]($style)"
show_always = true
style_root = "bold red"
style_user = "bold yellow"
